version: "3.8"

services:
  # Client application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:5000
    networks:
      - app-network

  # Server application
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - app-network

  # Redis server
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
